language: python
python:
  - "3.6"
sudo: enabled
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coveralls
# command to test
script:
  - ls
  - pylint Node/files
  - pylint Node/tests
  - python Node.node_test.py
  - coverage run --source=home Node.node_test.py test home
after_success:
  - coveralls
