language: python
python:
  - "3.6"
sudo: enabled
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coveralls
# command to test
script:
  - ls -a
  - pylint Node/files
  - pylint Node/tests
  - python Node.tests.node_test
  - coverage run --source=home Node.tests.node_test test home
after_success:
  - coveralls
